### PR TITLE
Sent date instead of received date in conversation list

### PR DESCRIPTION
**Pull request by piotrbernad**

### CODE REVIEW

**Comment by piotrbernad** [comment]
Second change is about clearing text from input toolbar. There are some situations when it shouldnt be cleared for example when there is no coversation to send message.

**Comment by kcoleman731** [comment]
@piotrbernad Thank you for this PR!

We sort the conversation list according to the conversations `lastMessage.receivedAt` property. If you would like the flexibility to change the sorting and also the date displayed in the cells, I would be very open to a PR that provides that functionality. 

Also, your PR has changes to the ruby version file and the podfile.lock which we wouldn't want to merge.

**Comment by kmahal** [comment]
Hey @piotrbernad any update on this PR?  If not we can close it out.  It also must be re-based since it's not mergeable anymore.

**Comment by kmahal** [comment]
@piotrbernad I'll be closing this out.  Feel free to re-open if you update this.

**Pull request closed without merging**
