### PR TITLE
Fix issue #1230

### PR DESCRIPTION
**Pull request by melbic**
Check if collection view isn’t already updated.
When updating collection view with inserts, it should only be updated if it doesn’t already contain the changes.
This pull request fixes issue #1230. 
There could be the same issue on LYRQueryControllerChangeTypeDelete, but we haven't any code to test it, so if there are cases where messages are deleted, feel free to add the code.

### CODE REVIEW

**Comment by jpmcglone** [comment]
@melbic can you please rebase off the latest `master` to get CI passing?

**Comment by ebobe** [comment]
I'm experiencing some crashes related to this. It'd be nice to get this merged for the next Layer release.

**Comment by melbic** [comment]
@jpmcglone @ebobe Sorry, I didn't have the time back then. Just merged the current master branch into this bugfix branch.

**Comment by Przytua** [comment]
I've fixed it with PR #1435 which was merged and released in v1.1.4 (https://github.com/layerhq/Atlas-iOS/releases/tag/v1.1.4) so I'm closing this PR.

**Pull request closed without merging**
