### PR TITLE
Dynamically size the Send Button

### LINKED ISSUE #942: Localized/Customized send button text truncated
The fixed width on the send button (static CGFloat const ATLRightAccessoryButtonWidth = 46.0f;) causes longer strings to get truncated. I'll try to create a fix tomorrow.
send

### PR DESCRIPTION
**Pull request by garhiggins**
This will allow for customization/localization of the send button text. fixes #942.

### CODE REVIEW

**Comment by kmahal** [comment]
@garhiggins this PR incorrectly sizes the button.  By having the size width defined in first appearance, the width is defined to be `40` by default, which compresses the button when displaying text.

**Comment by garhiggins** [comment]
I'm not an iOS developer (or, at the very least, I'm a very bad one ;) ), this was just what I hacked together to make it work for us. Are you saying the button text gets compressed by this change? Maybe a screenshot of what you're seeing would help me understand.

**Comment by kmahal** [comment]
@garhiggins see below.  When running your branch with no other configuration (default `Send` text):

simulator screen shot oct 13 2015 12 25 09 pm

**Comment by garhiggins** [comment]
yeah, that's unfortunate - not sure why it worked for us in our fork of atlas - probably related to the fact that I changed some stuff to drop the 'share location' button.  oh well.

**Comment by kmahal** [comment]
@garhiggins merged a feature implementation: https://github.com/layerhq/Atlas-iOS/pull/1022.

**Pull request closed without merging**
