### PR TITLE
Added ability to scale down image size.

### PR DESCRIPTION
**Pull request by timominous**

### CODE REVIEW

**Comment by kmahal** [comment]
@timominous we already set the `thumbnailSize` for the thumbnail images, which the developer can specify already.  The developer can also choose to not download the full size image in their implementation.  Is this pull request still necessary?  I see it's for the full image, but that's why we have the thumbnail for compression size.

**Comment by timominous** [comment]
@kmahal I just thought it would be better to have the option. The preview works great for the receiver as they are able to view the image almost instantly. However, it still means that the sender would have to send the full sized image before the receiver can see the preview. Also, I think users would prefer the larger image if a he/she chooses to implement a fullscreen preview (or save to library) module.

**Comment by kcoleman731** [comment]
@timominous I'm doing a bit of repo clean up and am going to close this PR unless you have any objections.

**Comment by timominous** [comment]
@kcoleman731 I have nothing against it. I'm closing it now.

**Pull request closed without merging**
