### PR TITLE
Fix broken Carthage builds

### PR DESCRIPTION
**Pull request by cliss**
There are a couple files that are missing from the Xcode project, which is causing a build failure.

* [`UICollectionView+ATLHelpers.h`](https://github.com/layerhq/Atlas-iOS/blob/master/Code/Utilities/UICollectionView%2BATLHelpers.h), added in [this commit](https://github.com/layerhq/Atlas-iOS/commit/a75f57ac63aeb063641d2ad5a0d1547b856b9023) from @Przytua
* [`UIView+ATLHelpers.h`](https://github.com/layerhq/Atlas-iOS/blob/master/Code/Utilities/UIView%2BATLHelpers.h), added in [this commit](https://github.com/layerhq/Atlas-iOS/commit/a75f57ac63aeb063641d2ad5a0d1547b856b9023) from @Przytua

I should also note [`UIMutableNotificationAction+ATLHelpers.h`](https://github.com/layerhq/Atlas-iOS/blob/master/Code/Utilities/UIMutableUserNotificationAction%2BATLHelpers.h) is in the file tree but not referenced anywhere in the project.

Additionally, the Carthage binary for `LayerKit` wasn't being linked, which caused downstream Carthage builds to break. This PR also fixes this problem.

⚠️ I didn't try downstream Cocoapods builds; you guys may wish to try those before you approve this PR ⚠️

### CODE REVIEW

**Comment by cliss** [comment]
It looks like this is a *possible* duplicate of #1441.

**Comment by cliss** [comment]
...and #1440.

**Comment by Przytua** [comment]
Please note that this is fixed in https://github.com/layerhq/Atlas-iOS/pull/1441

**Comment by cliss** [comment]
@Przytua as I [noted above](https://github.com/layerhq/Atlas-iOS/pull/1445#issuecomment-351194826). :) 

@daniel-maness looks like #1441 is waiting on your review; any chance we could get that merged? 😇

**Comment by daniel-maness** [comment]
Fixed and merged in #1441

**Pull request closed without merging**
