### PR TITLE
Respect marksMessagesAsRead property on ATLConversationViewController

### PR DESCRIPTION
**Pull request by dfinzer**
@kmahal Let me know if I'm missing any pieces here.

https://github.com/layerhq/Atlas-iOS/issues/964

### CODE REVIEW

**Comment by dfinzer** [comment]
@kmahal @blakewatters @kcoleman731 let me know if this looks reasonable

**Comment by kmahal** [comment]
@dfinzer looks good, just needs to be rebased.  The `Podfile.lock` cannot be merged, so rebase your branch on master and we'll get this merged in.  Thank you for the work.

**Comment by dfinzer** [comment]
@kmahal rebased, ready for merge. Thank you!

**Comment by kmahal** [comment]
@dfinzer merged. Thanks!

**Pull request merged**
